[project]
name = 'Cognitive-Substrate-Independence-Framework'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.experiential-fidelity-preservation]
path = 'contracts/experiential-fidelity-preservation.clar'
clarity_version = 2
epoch = 2.5

[contracts.mind-substrate-abstraction]
path = 'contracts/mind-substrate-abstraction.clar'
clarity_version = 2
epoch = 2.5

[contracts.thought-transference]
path = 'contracts/thought-transference.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
